provenance:
  title: "Provenance"
  description: "Provenance information allows researchers to understand data within the context of its origins and can be an indicator of quality, authenticity and timeliness."
  origin:
    title: "Origin Coverage"
    description: "Coverage by origin (geographical and situations)."
    datasetType:
      title: "Dataset type"
      description: "Select one or more dataset types. For each selected type, you may optionally add one or more sub-types that further describe the content."
      guidance: |
        Datasets can have multiple types. Each selected type has its own optional sub-types.

        Types and sub-types:

        - **Health and disease**
          Sub-types: Mental health; Cardiovascular; Cancer; Rare diseases; Metabolic and endocrine; Neurological;
          Reproductive; Maternity and neonatology; Respiratory; Immunity; Musculoskeletal; Vision; Renal and urogenital;
          Oral and gastrointestinal; Cognitive function; Hearing; Others.

        - **Treatments/Interventions**
          Sub-types: Vaccines; Preventive; Therapeutic; Others.

        - **Measurements/Tests**
          Sub-types: Laboratory; Other diagnostics.

        - **Imaging types**
          Sub-types: CT; MRI; PET; X-ray; Ultrasound; Pathology; Others.

        - **Imaging Area Of The Body**
          Sub-types: Head; Chest; Arm; Abdomen; Leg; Others.

        - **Omics**
          Sub-types: Proteomics; Transcriptomics; Epigenomics; Metabolomics; Metagenomics; Genomics; Lipidomics; Others.
          Note: If more than one Omics sub-type is selected, the catalogue may additionally tag the dataset as **Multiomics**.

        - **Socioeconomic**
          Sub-types: Education; Crime and justice; Ethnicity; Housing; Labour; Ageing; Economics; Marital status;
          Social support; Deprivation; Religion; Occupation; Finances; Family circumstance; Others.

        - **Lifestyle**
          Sub-types: Smoking; Physical activity; Dietary habits; Alcohol; Others.

        - **Registry**
          Sub-types: Disease registry (research); National disease registries and audits; Births and deaths; Others.

        - **Environment and energy**
          Sub-types: Not applicable.

        - **Information and communication**
          Sub-types: Not applicable.

        - **Politics**
          Sub-types: Not applicable.

      examples:
        - |
          Single type without sub-types:
          [
            { "name": "Environment and energy" }
          ]
        - |
          Multiple types with sub-types:
          [
            {
              "name": "Health and disease",
              "subTypes": ["Cancer", "Respiratory"]
            },
            {
              "name": "Imaging types",
              "subTypes": ["CT", "MRI"]
            },
            {
              "name": "Omics",
              "subTypes": ["Genomics", "Transcriptomics"]
            }
          ]
        - |
          Imaging area example:
          [
            {
              "name": "Imaging Area Of The Body",
              "subTypes": ["Chest", "Abdomen"]
            }
          ]

    # Note: `datasetSubType` is no longer a separate field. Sub-types are chosen per entry in `datasetType`.
summary:
  dataCustodian:
    title: "Dataset Custodian"
    description: "This is the organisation responsible for running or supporting the data access request process, as well as enquiries about a dataset. In most this will be the same as the HDR UK Organisation (Hub or Alliance Member). However, in some cases this will be different i.e. Tissue Directory are an HDR UK Gateway organisation but coordinate activities across a number of data publishers i.e. Cambridge Blood and Stem Cell Biobank."
  contactPoint:
    guidance: "Organisations are expected to provide a dedicated email address associated with the data access request process. If no contact point is provided in this field, this field will be defaulted to the teams support email provided in the teams setting.\\n**Note:** An employee's email address can only be provided on a temporary basis and if one is provided, **you must obtain explicit consent for this purpose**."
    examples:
      - "gateway@hdruk.ac.uk"
    title: "Contact point"
    description: "Please provide a valid email address that can be used to coordinate data access requests."
  doiName:
    guidance: "- Please note: This is **not** the DOI of the publication(s) associated with the dataset.\\n- All HDR UK registered **datasets** should either have a **(DOI)** or be working towards obtaining one.\\n- If a DOI is available, please provide the DOI.\\n- **What happens if I do not have a DOI?**: Contact your academic organisation to find out if there is an existing relationship with a DOI provider. If that is not available, sites such as figshare offer free services to mint a DOI for your dataset. Subsequent versions of the Metadata Exchange will provide a DOI minting service."
    title: "Digital Object Identifier (DOI) for dataset"
    examples: 
      - 10.1093/ije/dyx196
    description: "DOI associated to this dataset. Find out more about DOIs here: [https://www.doi.org/the-identifier/what-is-a-doi/](https://www.doi.org/the-identifier/what-is-a-doi/)"
  populationSize:
    guidance: "This number informs a filter for Researchers to differentiate dataset search results based on the number of people in the dataset, and does not pull from the **Observations** fields. The filter also allows for Researchers to search datasets which have no population size reported, but will **not** pull any population size captured in the **Observations** section."
    title: "Dataset population size"
    description: "Input the number of people captured within the dataset."
    examples: 
      - 1000
  keywords:
    guidance: "- Please provide **relevant** and **specific keywords** that can **improve the search engine optimization** of your dataset.\\n- Please **enter one keyword at a time** and click **Add New Field** to add further keywords.\\n- Text from the title is automatically included in the search, there is no need to include this in the keywords.\\n- Include words that researcher may include in their searches."
    title: "Keywords"
    examples: 
      - Outpatient Care
      - Socioeconomic Deprivation
      - Infant Morbidity 
      - Learning disability
      - Primary Care Prescription
      - Accident and Emergency Admissions
    description: "Please provide a list of relevant and specific keywords that can improve the search engine optimisation (SEO) of your dataset as a comma separated list. Notes: Onboarding portal will suggest keywords based on title, abstract and description. We are compiling a standardised list of keywords and synonyms across datasets to make filtering easier for users."
  title:
    guidance: "- The **title** should provide a short description of the dataset and be **unique** across the gateway.\\n- If your title is not unique, please **add a prefix with your organisation name or identifier** to differentiate it from other datasets within the Gateway.\\n- If an accronym is widely used the dataset name, please add it in brackets () at the end of the title.\\n- Good titles should summarise the content of the dataset and if relevant, **the region the dataset covers**.\\n- **Example**: North West London COVID-19 Patient Level Situation Report"
    examples:
      - "North West London COVID-19 Patient Level Situation Report"
      - "Scottish Morbidity Record (SMR)"
    title: "Title"
    description: "Title of the dataset limited to 150 characters. It should provide a short description of the dataset and be unique across the gateway. If your title is not unique, please add a prefix with your organisation name or identifier to differentiate it from other datasets within the Gateway. Good titles should summarise the content of the dataset and if relevant, the region the dataset covers."
  abstract:
    guidance: "- The abstract should provide a **clear and brief descriptive** signpost for researchers who are searching for data that may be relevant to their research.\\n- The abstract should allow the reader to determine the **scope of the data collection and accurately summarise its content**.\\n- Effective abstracts should **avoid long sentences and abbreviations** where possible.\\n- **Note**: Researchers will view Titles and the first line of Abstracts (list view) when searching for datasets and choosing whether to explore their content further.\\n- **Abstracts should be different from the full description** for a dataset.\\n- **Example**: CPRD Aurum contains primary care data contributed by General Practitioner (GP) practices using EMIS Web® including patient registration information and all care events that GPs have chosen to record as part of their usual medical practice."
    examples:
      - "CPRD Aurum contains primary care data contributed by General Practitioner (GP) practices using EMIS Web® including patient registration information and all care events that GPs have chosen to record as part of their usual medical practice."
    title: "Dataset abstract"
    description: "Provide a clear and brief descriptive signpost for researchers who are searching for data that may be relevant to their research. The abstract should allow the reader to determine the scope of the data collection and accurately summarise its content. The optimal length is one paragraph (limited to 255 characters) and effective abstracts should avoid long sentences and abbreviations where possible."
  organisation:
    identifier:
      guidance: "**Example**: https://ror.org/053fq8t95\\nIf your organisation does not have a ROR identifier please use the “suggest and institute” function here: https://docs.google.com/forms/d/e/1FAIpQLSdJYaMTCwS7muuTa-B_CnAtCSkKzt19lkirAKG4u7umH9Nosg/viewform"
      title: "identifier"
      description: "Please provide a Research Organization Registry (ROR) identifier (see https://ror.org/) for your organisation."
      examples:
        - "30f16703-28bc-4f45-9ce5-625d2d3db27d"
    name:
      guidance: In most this will be the same as the Team you have on the Gateway. However, in some cases this will be different. For example, Tissue Directory are a Team on the Gateway but coordinate activities across a number of Data Providers such as Cambridge Blood and Stem Cell Biobank.
      title: "Name of Data Custodian"
      description: "The organisation responsible for running or supporting the data access request process, as well as publishing and maintaining the metadata."
      examples:
        - "Health Data Research UK"
    logo:
      title: "Organisation Logo"
      description: "Please provide a logo associated with the Gateway Organisation using a valid URL. The following formats will be accepted .jpg, .png or .svg.  If a logo is not submitted this will default to the logo for the team submitting the metadata."
    description:
      title: "Organisation Description"
      description: "Please provide a URL that describes the organisation.  If a description is not provided this will default to the description of the team submitting the metadata."
    contactPoint:
      title: "contact point"
      description: "Organisation contact point(s) which will be used for receiving queries from HDR, and enquiries and data access requests from Researchers.  If a contact point is not provided this will default to the contact point for the team submitting the metadata."
      examples:
        - "test@test.co.uk"
    memberOf:
      title: "Organisation Membership"
      description: "Please indicate if the organisation is an Alliance Member or a Hub.  If this field is not submitted this will default to the membership for the team submitting the metadata."
  datasetAliases:
    title: "Dataset & BioSample alias"
    description: "Dataset & BioSample alias or alternate names."
    guidance: "Alternate name, acronym or other identifier for the Dataset and/or BioSamples."



