site_name: HDRUK Schema
theme:
  name: material
  palette:
    scheme: hdruk
  #custom_dir: overrides      
  #logo: images/favicon.png
  #favicon: images/favicon.png
  features:
    - navigation.sections
extra_css:
  - stylesheets/custom.css
  
nav:
  - Welcome: index.md
  - Gateway Data Model:
      Version 1.0: GWDM/1.0.md

plugins:
  - search
