identifier:
  title: "Dataset identifier"
  description: System dataset identifier
  examples:
    - "226fb3f1-4471-400a-8c39-2b66d46a39b6"
    - "https://web.www.healthdatagateway.org/dataset/226fb3f1-4471-400a-8c39-2b66d46a39b6"

version:
  title: "Dataset Version"
  description: "Dataset metadata version"
  examples:
    - "1.1.0"

summary:
  title:
    title: Title
    description: Title of the dataset limited to 150 characters. It should provide a short description of the dataset and be unique across the gateway. If your title is not unique, please add a prefix with your organisation name or identifier to differentiate it from other datasets within the Gateway. Please avoid acronyms wherever possible. Good titles should summarise the content of the dataset and if relevant, the region the dataset covers.
    examples:
      - North West London COVID-19 Patient Level Situation Report

  abstract:
    description: Provide a clear and brief descriptive signpost for researchers who are searching for data that may be relevant to their research. The abstract should allow the reader to determine the scope of the data collection and accurately summarise its content. The optimal length is one paragraph (limited to 255 characters) and effective abstracts should avoid long sentences and abbreviations where possible
    examples:
      - CPRD Aurum contains primary care data contributed by General Practitioner (GP) practices using EMIS Web® including patient registration information and all care events that GPs have chosen to record as part of their usual medical practice.
    title: Dataset Abstract

  publisher:
    description: This is the organisation responsible for running or supporting the data access request process, as well as publishing and maintaining the metadata. In most this will be the same as the HDR UK Organisation (Hub or Alliance Member). However, in some cases this will be different i.e. Tissue Directory are an HDR UK Gateway organisation but coordinate activities across a number of data publishers i.e. Cambridge Blood and Stem Cell Biobank.
    title: Dataset publisher

  contactPoint:
    description: "Please provide a valid email address that can be used to coordinate data access requests with the publisher. Organisations are expected to provide a dedicated email address associated with the data access request process. Notes- An employee's email address can only be provided on a temporary basis and if one is provided an explicit consent must be obtained for this purpose. Gateway Feature: If no contact point is provided in this field, this field will be defaulted to the teams support email provided in the teams setting."
    examples:
      - SAILDatabank@swansea.ac.uk
    title: Contact Point

  keywords:
    description: "Please provide a list of relevant and specific keywords that can improve the SEO of your dataset as a comma separated list. Notes: Onboarding portal will suggest keywords based on title, abstract and description. We are compiling a standardised list of keywords and synonyms across datasets to make filtering easier for users."
    title: Keywords

  alternateIdentifiers:
    description: "Alternate dataset identifiers or local identifiers"
    title: Alternate dataset identifiers

documentation:
  _description: Documentation can include a rich text description of the dataset or links to media such as documents, images, presentations, videos or links to data dictionaries, profiles or dashboards. Organisations are required to confirm that they have permission to distribute any additional media.
  _title: Documentation
  description:
    description: "A free-text description of the dataset. Gateway Feature: Keywords and text may be extracted out of the description and index for search"
    title: Description

  associatedMedia:
    description: "Please provide any media associated with the Gateway Organisation using a valid URI for the content. This is an opportunity to provide additional context that could be useful for researchers wanting to understand more about the dataset and its relevance to their research question. The following formats will be accepted .jpg, .png or .svg, .pdf, .xslx or .docx. Note: media asset can be hosted by the organisation or uploaded using the onboarding portal."
    examples:
      - PDF Document that describes study protocol
    title: Associated Media

  isPartOf:
    description: Please complete only if the dataset is part of a group or family
    examples:
      - Hospital Episodes Statistics datasets (A&E, APC, OP, AC MSDS).
    title: Group

accessibility:
  access:
    title: Access
    description: Metadata relating to access to this dataset
    accessRights:
      title: Access Rights
      description: Please provide details for the data access rights

    accessService:
      description: "Please provide a brief description of the data access services that are available including: environment that is currently available to researchers;additional consultancy and services;any indication of costs associated. If no environment is currently available, please indicate the current plans and timelines when and how data will be made available to researchers Note: This value will be used as default access environment for all datasets submitted by the organisation. However, there will be the opportunity to overwrite this value for each dataset."
      examples:
        - "https://cnfl.extge.co.uk/display/GERE/Research+Environment+User+Guide"
      title: Access Service

    accessRequestCost:
      description: "Please provide link(s) to a webpage detailing the commercial model for processing data access requests for the organisation (if available) Definition: Indication of commercial model or cost (in GBP) for processing each data access request by the data custodian."
      title: "Organisation Access Request Cost"

    deliveryLeadTime:
      description: "Please provide an indication of the typical processing times based on the types of requests typically received."
      title: "Access Request Duration"

    jurisdiction:
      description: Please use country code from ISO 3166-1 country codes and the associated ISO 3166-2 for regions, cities, states etc. for the country/state under whose laws the data subjects' data is collected, processed and stored.
      title: Jurisdiction

    dataController:
      description: "Data Controller means a person/entity who (either alone or jointly or in common with other persons/entities) determines the purposes for which and the way any Data Subject data, specifically personal data or are to be processed."
      title: Data Controller

    dataProcessor:
      description: "A Data Processor, in relation to any Data Subject data, specifically personal data, means any person/entity (other than an employee of the data controller) who processes the data on behalf of the data controller."
      title: Data Processor

  usage:
    title: Usage
    description: Data usage information
    dataUseLimitation:
      description: "Please provide an indication of consent permissions for datasets and/or materials, and relates to the purposes for which datasets and/or material might be removed, stored or used. NOTE: we have extended the DUO to include a value for NO LINKAGE"
      title: Data Use Limitation

    dataUseRequirements:
      description: Please indicate fit here are any additional conditions set for use if any, multiple requirements may be provided. Please ensure that these restrictions are documented in access rights information.
      title: Data Use Requirements

    resourceCreator:
      description: Please provide the text that you would like included as part of any citation that credits this dataset. This is typically just the name of the publisher.   No employee details should be provided.'
      title: Citation Requirements'

    investigations:
      title: Investigations

    isReferencedBy:
      description: "Please provide the keystone paper associated with the dataset. Also include a list of known citations, if available and should be links to existing resources where the dataset has been used or referenced. Please provide multiple entries, or if you are using a csv upload please provide them as a tab separated list."
      title: "Citations"

enrichmentAndLinkage:
  description: This section includes information about related datasets that may have previously been linked, as well as indicating if there is the opportunity to link to other datasets in the future. If a dataset has been enriched and/or derivations, scores and existing tools are available this section allows providers to indicate this to researchers.
  title: Enrichment and Linkage
  qualifiedRelation:
    description: "If applicable, please provide the DOI of other datasets that have previously been linked to this dataset and their availability. If no DOI is available, please provide the title of the datasets that can be linked, where possible using the same title of a dataset previously onboarded to the HOP. Note: If all the datasets from Gateway organisation can be linked please indicate “ALL” and the onboarding portal will automate linkage across the datasets submitted."
    title: Linked Datasets
  derivation:
    description: "Indicate if derived datasets or predefined extracts are available and the type of derivation available. Notes. Single or multiple dimensions can be provided as a derived extract alongside the dataset."
    title: Derivations
  tools:
    description: "Please provide the URL of any analysis tools or models that have been created for this dataset and are available for further use. Multiple tools may be provided. Note: We encourage users to adopt a model along the lines of https://www.ga4gh.org/news/tool-registry-service-api-enabling-an-interoperable-library-of-genomics-analysis-tools/"
    title: Tools
