identifier:
  title: "Dataset identifier"
  description: System dataset identifier
  examples:
    - "226fb3f1-4471-400a-8c39-2b66d46a39b6"
    - "https://web.www.healthdatagateway.org/dataset/226fb3f1-4471-400a-8c39-2b66d46a39b6"

version:
  title: "Dataset Version"
  description: "Dataset metadata version"
  examples:
    - "1.1.0"

summary:
  title:
    title: Title
    description: Title of the dataset limited to 150 characters. It should provide a short description of the dataset and be unique across the gateway. If your title is not unique, please add a prefix with your organisation name or identifier to differentiate it from other datasets within the Gateway. Please avoid acronyms wherever possible. Good titles should summarise the content of the dataset and if relevant, the region the dataset covers.
    examples:
      - North West London COVID-19 Patient Level Situation Report

  abstract:
    description: Provide a clear and brief descriptive signpost for researchers who are searching for data that may be relevant to their research. The abstract should allow the reader to determine the scope of the data collection and accurately summarise its content. The optimal length is one paragraph (limited to 255 characters) and effective abstracts should avoid long sentences and abbreviations where possible
    examples:
      - CPRD Aurum contains primary care data contributed by General Practitioner (GP) practices using EMIS Web® including patient registration information and all care events that GPs have chosen to record as part of their usual medical practice.
    title: Dataset Abstract

  publisher:
    description: This is the organisation responsible for running or supporting the data access request process, as well as publishing and maintaining the metadata. In most this will be the same as the HDR UK Organisation (Hub or Alliance Member). However, in some cases this will be different i.e. Tissue Directory are an HDR UK Gateway organisation but coordinate activities across a number of data publishers i.e. Cambridge Blood and Stem Cell Biobank.
    title: Dataset publisher

  contactPoint:
    description: "Please provide a valid email address that can be used to coordinate data access requests with the publisher. Organisations are expected to provide a dedicated email address associated with the data access request process. Notes- An employee's email address can only be provided on a temporary basis and if one is provided an explicit consent must be obtained for this purpose. Gateway Feature: If no contact point is provided in this field, this field will be defaulted to the teams support email provided in the teams setting."
    examples:
      - SAILDatabank@swansea.ac.uk
    title: Contact Point

  keywords:
    description: "Please provide a list of relevant and specific keywords that can improve the SEO of your dataset as a comma separated list. Notes: Onboarding portal will suggest keywords based on title, abstract and description. We are compiling a standardised list of keywords and synonyms across datasets to make filtering easier for users."
    title: Keywords

  alternateIdentifiers:
    description: "Alternate dataset identifiers or local identifiers"
    title: Alternate dataset identifiers

documentation:
  _description: Documentation can include a rich text description of the dataset or links to media such as documents, images, presentations, videos or links to data dictionaries, profiles or dashboards. Organisations are required to confirm that they have permission to distribute any additional media.
  _title: Documentation
  description:
    description: "A free-text description of the dataset. Gateway Feature: Keywords and text may be extracted out of the description and index for search"
    title: Description

  associatedMedia:
    description: "Please provide any media associated with the Gateway Organisation using a valid URI for the content. This is an opportunity to provide additional context that could be useful for researchers wanting to understand more about the dataset and its relevance to their research question. The following formats will be accepted .jpg, .png or .svg, .pdf, .xslx or .docx. Note: media asset can be hosted by the organisation or uploaded using the onboarding portal."
    examples:
      - PDF Document that describes study protocol
    title: Associated Media

  isPartOf:
    description: Please complete only if the dataset is part of a group or family
    examples:
      - Hospital Episodes Statistics datasets (A&E, APC, OP, AC MSDS).
    title: Group

enrichmentAndLinkage:
  description: This section includes information about related datasets that may have previously been linked, as well as indicating if there is the opportunity to link to other datasets in the future. If a dataset has been enriched and/or derivations, scores and existing tools are available this section allows providers to indicate this to researchers.
  title: Enrichment and Linkage
  qualifiedRelation:
    description: "If applicable, please provide the DOI of other datasets that have previously been linked to this dataset and their availability. If no DOI is available, please provide the title of the datasets that can be linked, where possible using the same title of a dataset previously onboarded to the HOP. Note: If all the datasets from Gateway organisation can be linked please indicate “ALL” and the onboarding portal will automate linkage across the datasets submitted."
    title: Linked Datasets
  derivation:
    description: "Indicate if derived datasets or predefined extracts are available and the type of derivation available. Notes. Single or multiple dimensions can be provided as a derived extract alongside the dataset."
    title: Derivations
  tools:
    description: "Please provide the URL of any analysis tools or models that have been created for this dataset and are available for further use. Multiple tools may be provided. Note: We encourage users to adopt a model along the lines of https://www.ga4gh.org/news/tool-registry-service-api-enabling-an-interoperable-library-of-genomics-analysis-tools/"
    title: Tools

coverage:
  title: Coverage
  typicalAgeRange:
    examples:
      - 18-90
      
accessibility:
  formatAndStandards:
    conformsTo:
      description: List standardised data models that the dataset has been stored in or transformed to, such as OMOP or FHIR. If the data is only available in a local format, please make that explicit. If you are using a standard that has not been included in the list, please use “other” and contact support desk to ask for an addition.
      examples:
        - "LOCAL,NHS DATA DICTIONARY"
      title: Conforms To

structuralMetadata:
  title: Structural Metadata
  description: Structural metadata about tables, columns and values
