Common: &common_definitions
  issued: &common_definitions_issued
    description: Datetime stamp of when this metadata version was initially issued
    title: Metadata Issued Datetime',
  modified: &common_definitions_modified
    description: Datetime stamp of when this metadata was last modified
    title: Last Modified Datetime
  revisions: &common_definitions_revisions
    description: A list of persistent identifiers and version numbers for previous versions of metadata for this dataset
    title: Metadata Version Revisions
    version:
      description: Version number used for previous version of this dataset
      title: revision version
      examples:
        - 6.0.0
    url:
      description: Some url with a reference to the record of a previous version of this dataset
      title: revision url
      examples:
        - https://api.service.nhs.uk/health-research-data-catalogue/datasetrevisions/841f7da2-b018-41f6-b4ae-2e0aadab6561

  organisation: &common_definitions_organisation
    identifier:
      description: "Please provide a Grid.ac identifier (see https://www.grid.ac/institutes) for your organisation. If your organisation does not have a Grid.ac identifier please use the “suggest and institute” function here: https://www.grid.ac/institutes#"
      title: "Organisation Identifier"

    name:
      description: Name of the organisation
      title: Organisation Name

    logo:
      description: Please provide a logo associated with the Gateway Organisation using a valid URL. The following formats will be accepted .jpg, .png or .svg.
      title: Organisation Logo

    description:
      description: Please provide a URL that describes the organisation.
      title: Organisation Description

    contactPoint:
      description: Organisation contact point(s)
      title: Organisation Contact Point

    memberOf:
      description: Please indicate if the organisation is an Alliance Member or a Hub.'
      title: Organisation Membership

  summary: &common_definitions_summary
    _description: Summary of metadata describing key pieces of information.
    _title: Summary

    title:
      title: Title
      description: The main title of the dataset
      examples:
        - Publications that mention HDR-UK (or any variant thereof) in Acknowledgements or Author Affiliations

    shortTitle:
      description: A shorter descriptive title of the dataset
      examples:
        - ONS 2011 Census Wales (CENW)
      title: Short Title

    doiName:
      title: DOI Name
      description: DOI associated to this dataset
      examples: 10.1093/ije/dyx196

    abstract:
      title: Abstract
      description: Longer abstract detailing the dataset.
      examples:
        - COVID-19 Key Worker Testing Results data is required by NHS Digital to support COVID-19 requests for linkage, analysis and dissemination to other organisations who require the data in a timely manner.

    keywords:
      title: Keywords
      description: Comma separated key words associated to this dataset.
      examples:
        - Preprints,Papers,HDR UK

    controlledKeywords:
      description: Keywords that have been filtered and limited
      title: Controlled Keywords

    contactPoint:
      description: email of a person who can be the main contact point of this dataset
      example:
        - blah.blah@blah.com
      title: Contact Point

    datasetType:
      description: What type of dataset is this?
      title: Dataset type

    description:
      description: Longer description of the dataset in detail
      examples:
        - Publications that mention HDR-UK (or any variant thereof) in Acknowledgements or Author Affiliations\n\nThis will include:\n- Papers\n- COVID-19 Papers\n- COVID-19 Preprint
      title: Description

    publisher:
      description: Link to details about the publisher of this dataset
      title: Publisher

  coverage: &common_definitions_coverage
    description: This information includes attributes for geographical and temporal coverage, cohort details etc. to enable a deeper understanding of the dataset content so that researchers can make decisions about the relevance of the underlying data.
    title: Coverage

    spatial:
      description: The geographical area covered by the dataset. It is recommended that links are to entries in a well-maintained gazetteer such as https://www.geonames.org/ or https://what3words.com/daring.lion.race.
      examples:
        - https://www.geonames.org/2635167/united-kingdom-of-great-britain-and-northern-ireland.html
      title: Geographic Coverage

    typicalAgeRange:
      description: "Please indicate the age range in whole years of participants in the dataset. Please provide range in the following format '[min age] – [max age]' where both the minimum and maximum are whole numbers (integers)."
      title: Age Range

    physicalSampleAvailability:
      description: Availability of physical samples associated with the dataset. If samples are available, please indicate the types of samples that are available. More than one type may be provided. If sample are not yet available, please provide “AVAILABILITY TO BE CONFIRMED”. If samples are not available, then please provide “NOT AVAILABLE”.
      examples:
        - "BONE MARROW"
      title: Physical Sample Availability

    followup:
      description: If known, what is the typical time span that a patient appears in the dataset (follow up period)
      title: Followup

    pathway:
      description: "Please indicate if the dataset is representative of the patient pathway and any limitations the dataset may have with respect to pathway coverage. This could include if the dataset is from a single speciality or area, a single tier of care, linked across two tiers (e.g. primary and secondary care), or an integrated care record covering the whole patient pathway."
      title: Pathway

  provenance: &common_definitions_provenance
    description: Provenance information allows researchers to understand data within the context of its origins and can be an indicator of quality, authenticity and timeliness.
    title: Provenance

    origin:
      description: Coverate by origin (geographical and situations)
      title: Origin Coverage
      purpose:
        description: Pleases indicate the purpose(s) that the dataset was collected.
        title: Purpose

      source:
        description: Pleases indicate the source of the data extraction
        title: Source

      collectionSituation:
        description: Pleases indicate the setting(s) where data was collected. Multiple settings may be provided
        title: Setting

    temporal:
      description: Dates and other temporal coverage information
      title: Temporal Coverage
      accrualPeriodicity:
        description: "Please indicate the frequency of distribution release. If a dataset is distributed regularly please choose a distribution release periodicity from the constrained list and indicate the next release date. When the release date becomes historical, a new release date will be calculated based on the publishing periodicity. If a dataset has been published and will remain static please indicate that it is static and indicated when it was released. If a dataset is released on an irregular basis or “on-demand” please indicate that it is Irregular and leave release date as null. If a dataset can be published in real-time or near-real-time please indicate that it is continuous and leave release date as null. Notes: see https://www.dublincore.org/specifications/dublin-core/collection-description/frequency/"
        title: Periodicity
      distributionReleaseDate:
        description: "Date of the latest release of the dataset. If this is a regular release i.e. quarterly, or this is a static dataset please complete this alongside Periodicity. If this is Irregular or Continuously released please leave this blank. Notes: Periodicity and release date will be used to determine when the next release is expected. E.g. if the release date is documented as 01/01/2020 and it is now 20/04/2020 and there is a quarterly release schedule, the latest release will be calculated as 01/04/2020."
        title: Release Date
      startDate:
        description: The start of the time period that the dataset provides coverage for. If there are multiple cohorts in the dataset with varying start dates, please provide the earliest date and use the description or the media attribute to provide more information.
        title: Start Date
      endDate:
        description: The end of the time period that the dataset provides coverage for. If the dataset is “Continuous” and has no known end date, please state continuous. If there are multiple cohorts in the dataset with varying end dates, please provide the latest date and use the description or the media attribute to provide more information.'
        title: End Date
      timeLag:
        description: Please indicate the typical time-lag between an event and the data for that event appearing in the dataset
        title: Time Lag

  accessibility: &common_definitions_accessibility
    description: Accessibility information allows researchers to understand access, usage, limitations, formats, standards and linkage or interoperability with toolsets.
    title: Accessibility
    usage: &common_definitions_usage
      description: This section includes information about how the data can be used and how it is currently being used
      title: Usage

    access: &common_definitions_access
      description: This section includes information about data access
      title: Access

    formatAndStandards: &common_definitions_formatAndStandards
      description: Section includes technical attributes for language vocabularies, sizes etc. and gives researchers facts about and processing the underlying data in the dataset.
      title: Format and Standards
      vocabularyEncodingScheme:
        description: "List any relevant terminologies / ontologies / controlled vocabularies, such as ICD 10 Codes, NHS Data Dictionary National Codes or SNOMED CT International, that are being used by the dataset. If the controlled vocabularies are local standards, please make that explicit. If you are using a standard that has not been included in the list, please use “other” and contact support desk to ask for an addition. Notes: More than one vocabulary may be provided."
        title: Controlled Vocabulary
      conformsTo:
        description: List standardised data models that the dataset has been stored in or transformed to, such as OMOP or FHIR. If the data is only available in a local format, please make that explicit. If you are using a standard that has not been included in the list, please use “other” and contact support desk to ask for an addition.
        title: Conforms To
      language:
        description: This should list all the languages in which the dataset metadata and underlying data is made available.
        title: Language
      format:
        description: "If multiple formats are available please specify. See application, audio, image, message, model, multipart, text, video, https://www.iana.org/assignments/media-types/media-types.xhtml Note: If your file format is not included in the current list of formats, please indicate other. If you are using the HOP you will be directed to a service desk page where you can request your additional format. If not please go to: https://metadata.atlassian.net/servicedesk/customer/portal/4 to request your format."
        title: Format

  observations: &common_definitions_obsservations
    description: |
      Multiple observations about the dataset may be provided and users are expected to provide at least one observation 
      (1..*). We will be supporting the schema.org observation model (https://schema.org/Observation) with default values. Users will be encouraged to provide their own statistical populations as the project progresses. 
      Example: 
            &lt;b&gt; Statistical Population 1 
            &lt;/b&gt; type: StatisticalPopulation populationType: Persons numConstraints: 0 
            &lt;b&gt; Statistical Population 2 &lt;/b&gt; type: StatisticalPopulation populationType: Events numConstraints: 0 &lt;b&gt; Statistical Population 3 &lt;/b&gt; type: StatisticalPopulation populationType: Findings numConstraints: 0 typeOf: Observation observedNode: &lt;b&gt; Statistical Population 1 &lt;/b&gt; measuredProperty: count measuredValue: 32937 observationDate: “2017”"
    title: Observations
    observedNode:
      description: Please select one of the following statistical populations for you observation
      examples:
        - "PERSONS"
      title: Statistical Population'
    measuredValue:
      description: "Please provide the population size associated with the population type the dataset i.e. 1000 people in a study, or 87 images (MRI) of Knee Usage Note: Used with Statistical Population, which specifies the type of the population in the dataset."
      title: Measured Value

    disambiguatingDescription:
      description: "If SNOMED CT term does not provide sufficient detail, please provide a description that disambiguates the population type."
      title: Disambiguating Description

    observationDate:
      description: Please provide the date that the observation was made. Some datasets may be continuously updated and the number of records will change regularly, so the observation date provides users with the date that the analysis or query was run to generate the particular observation. Multiple observations can be made i.e. an observation of cumulative COVID positive cases by specimen on the 1/1/2021 could be 2M. On the 8/1/2021 a new observation could be 2.1M. Users can add multiple observations.
      title: Observation Date

    measuredProperty:
      description: Initially this will be defaulted to "COUNT"
      title: Measured Property

  structuralMetadata:
    description: Descriptions of all tables and data elements that can be included in the dataset
    title: Structural Metadata

  dataClass:
    name:
      description: "The name of a table in a dataset."
      title: "Table Name"

    description:
      description: "A description of a table in a dataset."
      title: "Table Description"

    elements:
      description: "A list of data elements contained within a table in a dataset."
      title: "Data Elements"

  dataElement:
    name:
      description: "The name of a column in a table."
      title: Column Name

    dataType:
      description: "The data type of values in the column"
      title: Data Type

    description:
      description: "A description of a column in a table."
      title: Column Description

    sensitive:
      description: "A True or False value, indicating if the field is sensitive or not"
      title: Sensitive
