from enum import Enum

class DataUseLimitation(Enum):
    GENERAL_RESEARCH_USE = 'GENERAL RESEARCH USE'
    COMMERCIAL_RESEARCH_USE = 'COMMERCIAL RESEARCH USE'
    GENETIC_STUDIES_ONLY = 'GENETIC STUDIES ONLY'
    NO_GENERAL_METHODS_RESEARCH = 'NO GENERAL METHODS RESEARCH'
    NO_RESTRICTION = 'NO RESTRICTION'
    GEOGRAPHICAL_RESTRICTIONS = 'GEOGRAPHICAL RESTRICTIONS'
    INSTITUTION_SPECIFIC_RESTRICTIONS = 'INSTITUTION SPECIFIC RESTRICTIONS'
    NOT_FOR_PROFIT_USE = 'NOT FOR PROFIT USE'
    PROJECT_SPECIFIC_RESTRICTIONS = 'PROJECT SPECIFIC RESTRICTIONS'
    RESEARCH_SPECIFIC_RESTRICTIONS = 'RESEARCH SPECIFIC RESTRICTIONS'
    USER_SPECIFIC_RESTRICTION = 'USER SPECIFIC RESTRICTION'
    RESEARCH_USE_ONLY = 'RESEARCH USE ONLY'
    NO_LINKAGE = 'NO LINKAGE'


