from enum import Enum

class DataUseRequirements(Enum):
    COLLABORATION_REQUIRED = 'COLLABORATION REQUIRED'
    PROJECT_SPECIFIC_RESTRICTIONS = 'PROJECT SPECIFIC RESTRICTIONS'
    ETHICS_APPROVAL_REQUIRED = 'ETHICS APPROVAL REQUIRED'
    INSTITUTION_SPECIFIC_RESTRICTIONS = 'INSTITUTION SPECIFIC RESTRICTIONS'
    GEOGRAPHICAL_RESTRICTIONS = 'GEOGRAPHICAL RESTRICTIONS'
    PUBLICATION_MORATORIUM = 'PUBLICATION MORATORIUM'
    PUBLICATION_REQUIRED = 'PUBLICATION REQUIRED'
    RETURN_TO_DATABASE_OR_RESOURCE = 'RETURN TO DATABASE OR RESOURCE'
    TIME_LIMIT_ON_USE = 'TIME LIMIT ON USE'
    DISCLOSURE_CONTROL = 'DISCLOSURE CONTROL'
    NOT_FOR_PROFIT_USE = 'NOT FOR PROFIT USE'
    USER_SPECIFIC_RESTRICTION = 'USER SPECIFIC RESTRICTION'
    NoneType_None = None

class DataUseRequirementsV2(Enum):
    COLLABORATION_REQUIRED = 'Collaboration required'
    ETHICS_APPROVAL_REQUIRED = 'Ethics approval required'
    GEOGRAPHICAL_RESTRICTIONS = 'Geographical restrictions'
    INSTITUTION_SPECIFIC_RESTRICTIONS = 'Institution-specific restrictions'
    NOT_FOR_PROFIT_USE = 'Not for profit use'
    PROJECT_SPECIFIC_RESTRICTIONS = 'Project-specific restrictions'
    PUBLICATION_MORATORIUM = 'Publication moratorium'
    PUBLICATION_REQUIRED = 'Publication required'
    RETURN_TO_DATABASE_OR_RESOURCE = 'Return to database or resource'
    TIME_LIMIT_ON_USE = 'Time limit on use'
    USER_SPECIFIC_RESTRICTION = 'User-specific restriction'
