from enum import Enum

class Setting(Enum):
    CLINIC = 'CLINIC'
    PRIMARY_CARE = 'PRIMARY CARE'
    ACCIDENT_AND_EMERGENCY = 'ACCIDENT AND EMERGENCY'
    OUTPATIENTS = 'OUTPATIENTS'
    IN_PATIENTS = 'IN-PATIENTS'
    SERVICES = 'SERVICES'
    COMMUNITY = 'COMMUNITY'
    HOME = 'HOME'
    PRIVATE = 'PRIVATE'
    PHARMACY = 'PHARMACY'
    SOCIAL_CARE = 'SOCIAL CARE'
    LOCAL_AUTHORITY = 'LOCAL AUTHORITY'
    NATIONAL_GOVERNMENT = 'NATIONAL GOVERNMENT'
    OTHER = 'OTHER'


class SettingV2(Enum):
    COHORT_STUDY_TRIAL = 'Cohort, study, trial'
    CLINIC = 'Clinic'
    PRIMARY_CARE_REFERRALS = 'Primary care - Referrals'
    PRIMARY_CARE_CLINIC = 'Primary care - Clinic'
    PRIMARY_CARE_OUT_OF_HOURS = 'Primary care - Out of hours'
    SECONDARY_CARE_ACCIDENT_AND_EMERGENCY = 'Secondary care - Accident and Emergency'
    SECONDARY_CARE_OUTPATIENTS = 'Secondary care - Outpatients'
    SECONDARY_CARE_INPATIENTS = 'Secondary care - In-patients'
    SECONDARY_CARE_AMBULANCE = 'Secondary care - Ambulance'
    SECONDARY_CARE_ICU = 'Secondary care - ICU'
    PRESCRIBING_COMMUNITY_PHARMACY = 'Prescribing - Community pharmacy'
    PRESCRIBING_HOSPITAL = 'Prescribing - Hospital'
    PATIENT_REPORT_OUTCOME = 'Patient report outcome'
    WEARABLES = 'Wearables'
    LOCAL_AUTHORITY = 'Local authority'
    NATIONAL_GOVERNMENT = 'National government'
    COMMUNITY = 'Community'
    SERVICES = 'Services'
    HOME = 'Home'
    PRIVATE = 'Private'
    SOCIAL_CARE_HEALTH_CARE_AT_HOME = 'Social care - Health care at home'
    SOCIAL_CARE_OTHER_SOCIAL_DATA = 'Social care - Other social data'
    CENSUS = 'Census'
    OTHER = 'Other'
    NoneType_None = None
