from datetime import date, datetime
from enum import Enum
from typing import List, Optional, Union
from pydantic import AnyUrl, BaseModel, EmailStr, Field, constr

class DataUseRequirements(Enum):
    COLLABORATION_REQUIRED = 'COLLABORATION REQUIRED'
    PROJECT_SPECIFIC_RESTRICTIONS = 'PROJECT SPECIFIC RESTRICTIONS'
    ETHICS_APPROVAL_REQUIRED = 'ETHICS APPROVAL REQUIRED'
    INSTITUTION_SPECIFIC_RESTRICTIONS = 'INSTITUTION SPECIFIC RESTRICTIONS'
    GEOGRAPHICAL_RESTRICTIONS = 'GEOGRAPHICAL RESTRICTIONS'
    PUBLICATION_MORATORIUM = 'PUBLICATION MORATORIUM'
    PUBLICATION_REQUIRED = 'PUBLICATION REQUIRED'
    RETURN_TO_DATABASE_OR_RESOURCE = 'RETURN TO DATABASE OR RESOURCE'
    TIME_LIMIT_ON_USE = 'TIME LIMIT ON USE'
    DISCLOSURE_CONTROL = 'DISCLOSURE CONTROL'
    NOT_FOR_PROFIT_USE = 'NOT FOR PROFIT USE'
    USER_SPECIFIC_RESTRICTION = 'USER SPECIFIC RESTRICTION'
    NoneType_None = None


