Common: &common_definitions
  issued: &common_definitions_issued
    description: Datetime stamp of when this metadata version was initially issued
    title: Metadata Issued Datetime',
  modified: &common_definitions_modified
    description: Datetime stamp of when this metadata was last modified
    title: Last Modified Datetime
  revisions: &common_definitions_revisions
    description: A list of persistent identifiers and version numbers for previous versions of metadata for this dataset
    title: Metadata Version Revisions
    version:
      description: Version number used for previous version of this dataset
      title: revision version
      examples:
        - 6.0.0
    url:
      description: Some url with a reference to the record of a previous version of this dataset
      title: revision url
      examples:
        - https://api.service.nhs.uk/health-research-data-catalogue/datasetrevisions/841f7da2-b018-41f6-b4ae-2e0aadab6561

  summary: &common_definitions_summary
    _description: Summary of metadata describing key pieces of information.
    _title: Summary

    title:
      title: Title
      description: The main title of the dataset
      examples:
        - Publications that mention HDR-UK (or any variant thereof) in Acknowledgements or Author Affiliations

    shortTitle:
      description: A shorter descriptive title of the dataset
      examples:
        - ONS 2011 Census Wales (CENW)
      title: Short Title

    doiName:
      title: DOI Name
      description: DOI associated to this dataset
      examples: 10.1093/ije/dyx196

    abstract:
      title: Abstract
      description: Longer abstract detailing the dataset.
      examples:
        - COVID-19 Key Worker Testing Results data is required by NHS Digital to support COVID-19 requests for linkage, analysis and dissemination to other organisations who require the data in a timely manner.

    keywords:
      title: Keywords
      description: Comma separated key words associated to this dataset.
      examples:
        - Preprints,Papers,HDR UK

    controlledKeywords:
      description: Keywords that have been filtered and limited
      title: Controlled Keywords

    contactPoint:
      description: email of a person who can be the main contact point of this dataset
      example:
        - blah.blah@blah.com
      title: Contact Point

    datasetType:
      description: What type of dataset is this?
      title: Dataset type

    description:
      description: Longer description of the dataset in detail
      examples:
        - Publications that mention HDR-UK (or any variant thereof) in Acknowledgements or Author Affiliations\n\nThis will include:\n- Papers\n- COVID-19 Papers\n- COVID-19 Preprint
      title: Description

    publisher:
      description: Link to details about the publisher of this dataset
      title: Publisher

  coverage: &common_definitions_coverage
    description: This information includes attributes for geographical and temporal coverage, cohort details etc. to enable a deeper understanding of the dataset content so that researchers can make decisions about the relevance of the underlying data.
    title: Coverage

  provenance:
    description: Provenance information allows researchers to understand data within the context of its origins and can be an indicator of quality, authenticity and timeliness.
    title: Provenance

    origin:
      description: Coverate by origin (geographical and situations)
      title: Origin Coverage
      purpose:
        description: Pleases indicate the purpose(s) that the dataset was collected.
        title: Purpose

      source:
        description: Pleases indicate the source of the data extraction
        title: Source

      collectionSituation:
        description: Pleases indicate the setting(s) where data was collected. Multiple settings may be provided
        title: Setting

    temporal:
      description: Dates and other temporal coverage information
      title: Temporal Coverage
      accrualPeriodicity:
        description: "Please indicate the frequency of distribution release. If a dataset is distributed regularly please choose a distribution release periodicity from the constrained list and indicate the next release date. When the release date becomes historical, a new release date will be calculated based on the publishing periodicity. If a dataset has been published and will remain static please indicate that it is static and indicated when it was released. If a dataset is released on an irregular basis or “on-demand” please indicate that it is Irregular and leave release date as null. If a dataset can be published in real-time or near-real-time please indicate that it is continuous and leave release date as null. Notes: see https://www.dublincore.org/specifications/dublin-core/collection-description/frequency/"
        title: Periodicity
      distributionReleaseDate:
        description: "Date of the latest release of the dataset. If this is a regular release i.e. quarterly, or this is a static dataset please complete this alongside Periodicity. If this is Irregular or Continuously released please leave this blank. Notes: Periodicity and release date will be used to determine when the next release is expected. E.g. if the release date is documented as 01/01/2020 and it is now 20/04/2020 and there is a quarterly release schedule, the latest release will be calculated as 01/04/2020."
        title: Release Date
      startDate:
        description: The start of the time period that the dataset provides coverage for. If there are multiple cohorts in the dataset with varying start dates, please provide the earliest date and use the description or the media attribute to provide more information.
        title: Start Date
      endDate:
        description: The end of the time period that the dataset provides coverage for. If the dataset is “Continuous” and has no known end date, please state continuous. If there are multiple cohorts in the dataset with varying end dates, please provide the latest date and use the description or the media attribute to provide more information.'
        title: End Date
      timeLag:
        description: Please indicate the typical time-lag between an event and the data for that event appearing in the dataset
        title: Time Lag

  accessibility: &common_definitions_accessibility
    description: Accessibility information allows researchers to understand access, usage, limitations, formats, standards and linkage or interoperability with toolsets.
    title: Accessibility
    usage: &common_definitions_usage
      description: This section includes information about how the data can be used and how it is currently being used
      title: Usage

    access: &common_definitions_access
      description: This section includes information about data access
      title: Access

    formatAndStandards: &common_definitions_formatAndStandards
      description: Section includes technical attributes for language vocabularies, sizes etc. and gives researchers facts about and processing the underlying data in the dataset.
      title: Format and Standards

  observations:
    description: |
      Multiple observations about the dataset may be provided and users are expected to provide at least one observation 
      (1..*). We will be supporting the schema.org observation model (https://schema.org/Observation) with default values. Users will be encouraged to provide their own statistical populations as the project progresses. 
      Example: 
            &lt;b&gt; Statistical Population 1 
            &lt;/b&gt; type: StatisticalPopulation populationType: Persons numConstraints: 0 
            &lt;b&gt; Statistical Population 2 &lt;/b&gt; type: StatisticalPopulation populationType: Events numConstraints: 0 &lt;b&gt; Statistical Population 3 &lt;/b&gt; type: StatisticalPopulation populationType: Findings numConstraints: 0 typeOf: Observation observedNode: &lt;b&gt; Statistical Population 1 &lt;/b&gt; measuredProperty: count measuredValue: 32937 observationDate: “2017”"
    title: Observations

  structuralMetadata:
    description: Descriptions of all tables and data elements that can be included in the dataset
    title: Structural Metadata

GWDM:
  v1p0: &gwdm_1p0_definitions
    <<: *common_definitions
    required:
      description: Required metadata needed for the GWDM
      title: Required
      gatewayId:
        description: Associated identifier (number) that is the BigInt key in our SQL database for the dataset version associated with this metadata
        title: Gateway Identifier
        examples:
          - 101
      gatewayPid:
        description: A unique persistent identifier for the metadata version. This is a 128-bit unique identifiers, as 32 hexadecimal digits separated by hyphens
        title: Gateway Persistent Identifier
        examples:
          - 550e8400-e29b-41d4-a716-446655440000
      issued: *common_definitions_issued
      modified: *common_definitions_modified
      revisions: *common_definitions_revisions
    linkage:
      description: Linkage between datasets, other gateway entities and papers
      title: Linkage

  v1p1: &gwdm_1p1_definitions
    <<: *gwdm_1p0_definitions

  v1p2: &gwdm_1p2_definitions
    <<: *gwdm_1p1_definitions

HDRUK:
  v2p1p2: &hdruk_2p1p2_definitions
    <<: *common_definitions
    identifier:
      description: System dataset identifier
      examples:
        - "226fb3f1-4471-400a-8c39-2b66d46a39b6"
        - "https://web.www.healthdatagateway.org/dataset/226fb3f1-4471-400a-8c39-2b66d46a39b6"
      title: "Dataset identifier"
    version:
      description: "Dataset metadata version"
      examples:
        - "1.1.0"
      title: "Dataset Version"
    summary:
      <<: *common_definitions_summary
      #override the common definition with more detailed descriptions for the public schema
      title:
        title: Title
        description: Title of the dataset limited to 150 characters. It should provide a short description of the dataset and be unique across the gateway. If your title is not unique, please add a prefix with your organisation name or identifier to differentiate it from other datasets within the Gateway. Please avoid acronyms wherever possible. Good titles should summarise the content of the dataset and if relevant, the region the dataset covers.
        examples:
          - North West London COVID-19 Patient Level Situation Report

      abstract:
        description: Provide a clear and brief descriptive signpost for researchers who are searching for data that may be relevant to their research. The abstract should allow the reader to determine the scope of the data collection and accurately summarise its content. The optimal length is one paragraph (limited to 255 characters) and effective abstracts should avoid long sentences and abbreviations where possible
        examples:
          - CPRD Aurum contains primary care data contributed by General Practitioner (GP) practices using EMIS Web® including patient registration information and all care events that GPs have chosen to record as part of their usual medical practice.
        title: Dataset Abstract

      publisher:
        description: This is the organisation responsible for running or supporting the data access request process, as well as publishing and maintaining the metadata. In most this will be the same as the HDR UK Organisation (Hub or Alliance Member). However, in some cases this will be different i.e. Tissue Directory are an HDR UK Gateway organisation but coordinate activities across a number of data publishers i.e. Cambridge Blood and Stem Cell Biobank.
        title: Dataset publisher

      contactPoint:
        description: "Please provide a valid email address that can be used to coordinate data access requests with the publisher. Organisations are expected to provide a dedicated email address associated with the data access request process. Notes- An employee's email address can only be provided on a temporary basis and if one is provided an explicit consent must be obtained for this purpose. Gateway Feature: If no contact point is provided in this field, this field will be defaulted to the teams support email provided in the teams setting."
        examples:
          - SAILDatabank@swansea.ac.uk
        title: Contact Point

      keywords:
        description: "Please provide a list of relevant and specific keywords that can improve the SEO of your dataset as a comma separated list. Notes: Onboarding portal will suggest keywords based on title, abstract and description. We are compiling a standardised list of keywords and synonyms across datasets to make filtering easier for users."
        title: Keywords

      alternateIdentifiers:
        description: "Alternate dataset identifiers or local identifiers"
        title: Alternate dataset identifiers
    documentation:
      _description: Documentation can include a rich text description of the dataset or links to media such as documents, images, presentations, videos or links to data dictionaries, profiles or dashboards. Organisations are required to confirm that they have permission to distribute any additional media.
      _title: Documentation
      description:
        description: "A free-text description of the dataset. Gateway Feature: Keywords and text may be extracted out of the description and index for search"
        title: Description

      associatedMedia:
        description: "Please provide any media associated with the Gateway Organisation using a valid URI for the content. This is an opportunity to provide additional context that could be useful for researchers wanting to understand more about the dataset and its relevance to their research question. The following formats will be accepted .jpg, .png or .svg, .pdf, .xslx or .docx. Note: media asset can be hosted by the organisation or uploaded using the onboarding portal."
        examples:
          - PDF Document that describes study protocol
        title: Associated Media

      isPartOf:
        description: Please complete only if the dataset is part of a group or family
        examples:
          - Hospital Episodes Statistics datasets (A&E, APC, OP, AC MSDS).
        title: Group
    coverage:
      <<: *common_definitions_coverage
      spatial:
        description: The geographical area covered by the dataset. It is recommended that links are to entries in a well-maintained gazetteer such as https://www.geonames.org/ or https://what3words.com/daring.lion.race.
        examples:
          - https://www.geonames.org/2635167/united-kingdom-of-great-britain-and-northern-ireland.html
        title: Geographic Coverage

      typicalAgeRange:
        description: "Please indicate the age range in whole years of participants in the dataset. Please provide range in the following format '[min age] – [max age]' where both the minimum and maximum are whole numbers (integers)."
        title: Age Range

      physicalSampleAvailability:
        description: Availability of physical samples associated with the dataset. If samples are available, please indicate the types of samples that are available. More than one type may be provided. If sample are not yet available, please provide “AVAILABILITY TO BE CONFIRMED”. If samples are not available, then please provide “NOT AVAILABLE”.
        examples:
          - "BONE MARROW"
        title: Physical Sample Availability

      followup:
        description: If known, what is the typical time span that a patient appears in the dataset (follow up period)
        title: Followup

      pathway:
        description: "Please indicate if the dataset is representative of the patient pathway and any limitations the dataset may have with respect to pathway coverage. This could include if the dataset is from a single speciality or area, a single tier of care, linked across two tiers (e.g. primary and secondary care), or an integrated care record covering the whole patient pathway."
        title: Pathway
    accessibility:
      <<: *common_definitions_accessibility
      access:
        title: Access
        description: Metadat relating to access to this dataset
        usage:
          dataUseLimitation:
            description: "Please provide an indication of consent permissions for datasets and/or materials, and relates to the purposes for which datasets and/or material might be removed, stored or used. NOTE: we have extended the DUO to include a value for NO LINKAGE"
            title: Data Use Limitation

          dataUseRequirements:
            description: Please indicate fit here are any additional conditions set for use if any, multiple requirements may be provided. Please ensure that these restrictions are documented in access rights information.
            title: Data Use Requirements

          resourceCreator:
            description: Please provide the text that you would like included as part of any citation that credits this dataset. This is typically just the name of the publisher.   No employee details should be provided.'
            title: Citation Requirements'

          investigations:
            title: Investigations

          isReferencedBy:
            description: "Please provide the keystone paper associated with the dataset. Also include a list of known citations, if available and should be links to existing resources where the dataset has been used or referenced. Please provide multiple entries, or if you are using a csv upload please provide them as a tab separated list."
            title: "Citations"
    enrichmentAndLinkage:
      description: This section includes information about related datasets that may have previously been linked, as well as indicating if there is the opportunity to link to other datasets in the future. If a dataset has been enriched and/or derivations, scores and existing tools are available this section allows providers to indicate this to researchers.
      title: Enrichment and Linkage
