
summary:

  abstract:
    description: Provide a clear and brief descriptive signpost for researchers who are searching for data that may be relevant to their research. The abstract should allow the reader to determine the scope of the data collection and accurately summarise its content. The optimal length is one paragraph (limited to 255 characters) and effective abstracts should avoid long sentences and abbreviations where possible
    examples:
      - CPRD Aurum contains primary care data contributed by General Practitioner (GP) practices using EMIS Web® including patient registration information and all care events that GPs have chosen to record as part of their usual medical practice.
    title: Dataset abstract

  dataProvider:
    description: This is the organisation responsible for running or supporting the data access request process, as well as publishing and maintaining the metadata. In most this will be the same as the HDR UK Organisation (Hub or Alliance Member). However, in some cases this will be different i.e. Tissue Directory are an HDR UK Gateway organisation but coordinate activities across a number of data publishers i.e. Cambridge Blood and Stem Cell Biobank.
    title: Dataset provider

  organisation:
    identifier:
      description: "Please provide a Research Organization Registry (ROR) identifier (see https://ror.org/) for your organisation."
      title: identifier

    name:
      description: The organisation responsible for running or supporting the data access request process, as well as publishing and maintaining the metadata.
      title: Name of Data Provider

    logo:
      description: Please provide a logo associated with the Gateway Organisation using a valid URL. The following formats will be accepted .jpg, .png or .svg.
      title: Organisation Logo

    description:
      description: Please provide a URL that describes the organisation.
      title: Organisation Description

    contactPoint:
      description: Organisation contact point(s) which will be used for receiving queries from HDR, and enquiries and data access requests from Researchers.
      title: contact point

    memberOf:
      description: Please indicate if the organisation is an Alliance Member or a Hub.'
      title: Organisation Membership

  contactPoint:
    description: Please provide a valid email address that can be used to coordinate data access requests.
    examples:
      - SAILDatabank@swansea.ac.uk
    title: Contact point
  
  doiName:
    description: DOI associated to this dataset
    title: DOI for dataset

  populationSize:
    description: Input the number of people captured within the dataset
    title: Dataset population size

documentation:
  _description: Documentation can include a rich text description of the dataset or links to media such as documents, images, presentations, videos or links to data dictionaries, profiles or dashboards. Organisations are required to confirm that they have permission to distribute any additional media.
  _title: Documentation
  description:
    description: "A free-text description of the dataset. Gateway Feature: Keywords and text may be extracted out of the description and index for search"
    title: Description

  associatedMedia:
    description: "Please provide any media associated with the Gateway Organisation using a valid URI for the content. This is an opportunity to provide additional context that could be useful for researchers wanting to understand more about the dataset and its relevance to their research question. The following formats will be accepted .jpg, .png or .svg, .pdf, .xslx or .docx. Note: media asset can be hosted by the organisation or uploaded using the onboarding portal."
    examples:
      - PDF Document that describes study protocol
    title: Associated media

coverage:
  spatial:
    description: The geographical area covered by the dataset. It is recommended that links are to entries in a well-maintained gazetteer such as https://www.geonames.org/ or https://what3words.com/daring.lion.race.
    examples:
      - https://www.geonames.org/2635167/united-kingdom-of-great-britain-and-northern-ireland.html
    title: Geographic coverage
  
  typicalAgeRange:
    description: "Please indicate the age range in whole years of participants in the dataset. Please provide range in the following format '[min age] – [max age]' where both the minimum and maximum are whole numbers (integers)."
    title: Age range

  followup:
    description: If known, what is the typical time span that a patient appears in the dataset (follow up period)
    title: Follow-up

  pathway:
    description: "Please indicate if the dataset is representative of the patient pathway and any limitations the dataset may have with respect to pathway coverage. This could include if the dataset is from a single speciality or area, a single tier of care, linked across two tiers (e.g. primary and secondary care), or an integrated care record covering the whole patient pathway."
    title: Patient pathway description

  datasetCompleteness:
    description: The URL where a Researcher can learn more about the completeness of the dataset.
    title: Dataset coverage/completeness/quality
  
provenance:
  description: Provenance information allows researchers to understand data within the context of its origins and can be an indicator of quality, authenticity and timeliness.
  title: Provenance

  origin:
    description: Coverate by origin (geographical and situations)
    title: Origin Coverage
    purpose:
      description: Please indicate the purpose(s) that the dataset was collected.
      title: Purpose of dataset collection

    source:
      description: Please indicate the source of the data extraction
      title: Source of data extraction
    
    collectionSource:
        description: Please indicate the setting(s) where data was collected. Multiple settings may be provided
        title: Collection source setting

    datasetType:
      description: The topic areas to which the dataset content relates.
      title: Dataset type

    datasetSubType:
      description: The sub-type of the dataset content.
      title: Dataset sub-type
    
    imageContrast:
      description: Indicate whether usage of imaging contrast is captured within the dataset.
      title: Image contrast

  temporal:
    description: Dates and other temporal coverage information
    title: Temporal Coverage
    publishingFrequency:
      title: Publishing frequency
      description: "Please indicate the frequency of distribution release. If a dataset is distributed regularly please choose a distribution release periodicity from the constrained list and indicate the next release date. When the release date becomes historical, a new release date will be calculated based on the publishing periodicity. If a dataset has been published and will remain static please indicate that it is static and indicated when it was released. If a dataset is released on an irregular basis or “on-demand” please indicate that it is Irregular and leave release date as null. If a dataset can be published in real-time or near-real-time please indicate that it is continuous and leave release date as null. Notes: see https://www.dublincore.org/specifications/dublin-core/collection-description/frequency/"
    distributionReleaseDate:
      description: "Date of the latest release of the dataset. If this is a regular release i.e. quarterly, or this is a static dataset please complete this alongside Periodicity. If this is Irregular or Continuously released please leave this blank. Notes: Periodicity and release date will be used to determine when the next release is expected. E.g. if the release date is documented as 01/01/2020 and it is now 20/04/2020 and there is a quarterly release schedule, the latest release will be calculated as 01/04/2020."
      title: Distribution release date
    startDate:
      description: The start of the time period that the dataset provides coverage for. If there are multiple cohorts in the dataset with varying start dates, please provide the earliest date and use the description or the media attribute to provide more information.
      title: Start date
    endDate:
      description: The end of the time period that the dataset provides coverage for. If the dataset is “Continuous” and has no known end date, please state continuous. If there are multiple cohorts in the dataset with varying end dates, please provide the latest date and use the description or the media attribute to provide more information.'
      title: End date
    timeLag:
      description: Please indicate the typical time-lag between an event and the data for that event appearing in the dataset
      title: Time lag