name: Pytest

on: [push]
#  push:
#    branches:
#      - main  # Modify this branch name as needed
#  pull_request:
#    branches:
#      - main  # Modify this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  

    - name: Run pytest
      run: |
        cd hdr_schemata/tests/
        pytest  
