name: Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  

    - name: Install schema module
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install -e .

    - name: Test package
      run: |
         cd hdr_schemata/tests/
         python -c 'from hdr_schemata.models.HDRUK import Hdruk212'

    - name: Check location
      run: |
        pwd
        ls ../examples
        ls ../examples/HDRUK
        ls ../examples/HDRUK/2.1.2
         
    - name: Run pytest
      run: |
        pytest  
